<a href="https://colab.research.google.com/github/JesseRed/Colab/blob/master/Gan_conv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%tensorflow_version 2.0
import numpy as np
import tensorflow as tf
import tensorflow_datasets as tfds
import matplotlib.pyplot as plt

`%tensorflow_version` only switches the major version: `1.x` or `2.x`.
You set: `2.0`. This will be interpreted as: `2.x`.


TensorFlow 2.x selected.


#Get the Data

In [0]:
buffer_size = 1000
batch_size = 32
dataset = tfds.load('fashion_mnist',split='train')
ds = dataset.map(lambda item: item['image']/255)
ds = ds.shuffle(buffer_size).batch(batch_size, drop_remainder = True).prefetch(1)

#Generator


In [0]:
coding_size = 100
inputs = tf.keras.Input(shape=(coding_size,))
x = tf.keras.layers.Dense(7*7*128, activation='selu')(inputs)
x = tf.keras.layers.Reshape((7,7,128))(x)
x = tf.keras.layers.BatchNormalization()(x)
x = tf.keras.layers.Conv2DTranspose(64, kernel_size = 5, strides = 2, padding = 'same', activation= 'selu')(x)
x = tf.keras.layers.BatchNormalization()(x)
outputs = tf.keras.layers.Conv2DTranspose(1, kernel_size=5, strides =2, padding='same',activation = 'tanh')(x)
generator = tf.keras.Model(inputs=inputs, outputs=outputs)

In [4]:
tf.math.maximum(ds)

TypeError: ignored

In [15]:
m = 0
for elem in ds.as_numpy_iterator():
  t = np.max(elem)
  if t>m:
    m = t
print(m)


1.0


In [12]:
print(type(l))
print(l[1])


<class 'list'>
[[[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
 

In [9]:
tf.keras.backend.max(ds)

ValueError: ignored